"""initial

Revision ID: abbad8dfee92
Revises: 
Create Date: 2026-09-15 14:50:21.611224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbad8dfee92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('trips', sa.Integer(), nullable=False),
    sa.Column('last_trip', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'vip', 'idle', name='customer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager_spends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager', sa.String(length=120), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'employee', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('new_lead', 'proposal_sent', 'booked_prepay', 'paid_processing', 'ready_delivered', 'won', name='lead_status'), nullable=False),
    sa.Column('assignee', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('hotel', sa.String(length=200), nullable=False),
    sa.Column('flight_dates', sa.String(length=200), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children_ages', sa.String(length=120), nullable=False),
    sa.Column('passport_expiry', sa.String(length=64), nullable=False),
    sa.Column('net_cost', sa.Float(), nullable=False),
    sa.Column('gross_price', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount_uzs', sa.Float(), nullable=False),
    sa.Column('ticket_time_limit', sa.String(length=64), nullable=False),
    sa.Column('hotel_cancel_deadline', sa.String(length=64), nullable=False),
    sa.Column('full_payment_deadline', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('new', 'confirmed', 'paid', 'completed', 'cancelled', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tours')
    op.drop_table('manager_spends')
    op.drop_table('customers')
    # ### end Alembic commands ###
