"""leads: flight dates, currency, validation

Revision ID: dabff57f1294
Revises: abbad8dfee92
Create Date: 2026-09-15 16:28:10.484749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabff57f1294'
down_revision: Union[str, Sequence[str], None] = 'abbad8dfee92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    currency_enum = sa.Enum('USD', 'UZS', name='currency')
    currency_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('leads', sa.Column('flight_start', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('leads', sa.Column('flight_end', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('leads', sa.Column('currency', currency_enum, nullable=False, server_default='USD'))
    op.add_column('leads', sa.Column('exchange_rate', sa.Float(), nullable=False, server_default='12800'))

    # Eski qatorlarda uzun matn bo'lsa qisqartirish (type change xatosiz o'tsin)
    op.execute("UPDATE leads SET phone = LEFT(phone, 32), passport_expiry = LEFT(passport_expiry, 10), "
               "ticket_time_limit = LEFT(ticket_time_limit, 16), hotel_cancel_deadline = LEFT(hotel_cancel_deadline, 10), "
               "full_payment_deadline = LEFT(full_payment_deadline, 10)")

    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('leads', 'passport_expiry',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('leads', 'ticket_time_limit',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('leads', 'hotel_cancel_deadline',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('leads', 'full_payment_deadline',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_column('leads', 'flight_dates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('flight_dates', sa.VARCHAR(length=200), autoincrement=False, nullable=False, server_default=''))
    op.alter_column('leads', 'full_payment_deadline',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('leads', 'hotel_cancel_deadline',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('leads', 'ticket_time_limit',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('leads', 'passport_expiry',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('leads', 'phone',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('leads', 'exchange_rate')
    op.drop_column('leads', 'currency')
    op.drop_column('leads', 'flight_end')
    op.drop_column('leads', 'flight_start')
    sa.Enum(name='currency').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
