import type {
  Booking,
  Customer,
  DashboardStats,
  Lead,
  ManagerSpend,
  Tour,
  User,
} from "./types";
import { computeFinance } from "./finance";

export const DEMO_USERS: Record<string, User & { password: string }> = {
  "admin@agency.uz": {
    id: "u1",
    name: "Amir Admin",
    email: "admin@agency.uz",
    role: "admin",
    password: "admin123",
  },
  "employee@agency.uz": {
    id: "u2",
    name: "Sara Employee",
    email: "employee@agency.uz",
    role: "employee",
    password: "emp123",
  },
};

export const MOCK_TOURS: Tour[] = [
  {
    id: "t1",
    title: "Istanbul weekends",
    country: "Turkiya",
    city: "Istanbul",
    durationDays: 5,
    basePrice: 980,
    note: "Aviabilet + 3★ mehmonxona",
  },
  {
    id: "t2",
    title: "Dubai family",
    country: "BAA",
    city: "Dubai",
    durationDays: 7,
    basePrice: 1850,
    note: "Oilaviy paket, 4★",
  },
  {
    id: "t3",
    title: "Antalya sun",
    country: "Turkiya",
    city: "Antalya",
    durationDays: 8,
    basePrice: 1100,
    note: "All inclusive",
  },
  {
    id: "t4",
    title: "Paris classic",
    country: "Fransiya",
    city: "Paris",
    durationDays: 6,
    basePrice: 2400,
    note: "Markaziy mehmonxona",
  },
];

function lead(
  partial: Partial<Lead> &
    Pick<
      Lead,
      "id" | "name" | "phone" | "tourId" | "status" | "assignee" | "createdAt"
    >,
): Lead {
  return {
    id: partial.id,
    name: partial.name,
    phone: partial.phone,
    tourId: partial.tourId,
    status: partial.status,
    assignee: partial.assignee,
    createdAt: partial.createdAt,
    country: partial.country ?? "",
    city: partial.city ?? "",
    hotel: partial.hotel ?? "",
    flightDates: partial.flightDates ?? "",
    adults: partial.adults ?? 2,
    childrenAges: partial.childrenAges ?? "",
    passportExpiry: partial.passportExpiry ?? "",
    netCost: partial.netCost ?? 0,
    grossPrice: partial.grossPrice ?? 0,
    paidAmount: partial.paidAmount ?? 0,
    paidAmountUzs: partial.paidAmountUzs ?? 0,
    ticketTimeLimit: partial.ticketTimeLimit ?? "",
    hotelCancelDeadline: partial.hotelCancelDeadline ?? "",
    fullPaymentDeadline: partial.fullPaymentDeadline ?? "",
  };
}

export const MOCK_LEADS: Lead[] = [
  lead({
    id: "l1",
    name: "Jasur Karimov",
    phone: "+998 90 111 22 33",
    tourId: "t1",
    status: "new_lead",
    assignee: "Sara",
    createdAt: "2026-09-10",
    country: "Turkiya",
    city: "Istanbul",
    flightDates: "2026-10-12 — 2026-10-17",
    adults: 2,
    netCost: 900,
    grossPrice: 1200,
  }),
  lead({
    id: "l2",
    name: "Nilufar Yusupova",
    phone: "+998 93 444 55 66",
    tourId: "t2",
    status: "new_lead",
    assignee: "Sara",
    createdAt: "2026-09-11",
    country: "BAA",
    city: "Dubai",
    flightDates: "2026-11-01 — 2026-11-08",
    adults: 2,
    childrenAges: "5, 8",
    netCost: 1600,
    grossPrice: 2400,
  }),
  lead({
    id: "l3",
    name: "Bekzod Aliyev",
    phone: "+998 97 777 88 99",
    tourId: "t3",
    status: "proposal_sent",
    assignee: "Sara",
    createdAt: "2026-09-08",
    country: "Turkiya",
    city: "Antalya",
    hotel: "Lara Beach",
    flightDates: "2026-09-20 — 2026-09-28",
    adults: 2,
    netCost: 820,
    grossPrice: 980,
  }),
  lead({
    id: "l4",
    name: "Madina Rakhimova",
    phone: "+998 91 222 33 44",
    tourId: "t2",
    status: "booked_prepay",
    assignee: "Amir",
    createdAt: "2026-09-05",
    country: "Malayziya",
    city: "Kuala Lumpur",
    hotel: "KL Suites",
    flightDates: "2026-11-12 — 2026-11-20",
    adults: 1,
    netCost: 1300,
    grossPrice: 1650,
    paidAmount: 500,
    paidAmountUzs: 6300000,
    ticketTimeLimit: "2026-09-15 18:00",
    hotelCancelDeadline: "2026-10-20",
    fullPaymentDeadline: "2026-10-25",
  }),
  lead({
    id: "l5",
    name: "Otabek Tursunov",
    phone: "+998 95 555 66 77",
    tourId: "t4",
    status: "paid_processing",
    assignee: "Amir",
    createdAt: "2026-09-01",
    country: "Koreya",
    city: "Seoul",
    hotel: "Myeongdong Inn",
    flightDates: "2026-09-28 — 2026-10-05",
    adults: 2,
    passportExpiry: "2029-04-01",
    netCost: 2600,
    grossPrice: 3100,
    paidAmount: 3100,
    paidAmountUzs: 39060000,
    fullPaymentDeadline: "2026-09-12",
  }),
  lead({
    id: "l6",
    name: "Dilshoda Nazarova",
    phone: "+998 88 999 00 11",
    tourId: "t4",
    status: "ready_delivered",
    assignee: "Sara",
    createdAt: "2026-08-28",
    country: "Fransiya",
    city: "Paris",
    hotel: "Le Marais",
    flightDates: "2026-10-02 — 2026-10-08",
    adults: 2,
    passportExpiry: "2030-01-15",
    netCost: 2200,
    grossPrice: 2800,
    paidAmount: 2800,
    paidAmountUzs: 35280000,
  }),
  lead({
    id: "l7",
    name: "Sevara Ismailova",
    phone: "+998 99 666 77 88",
    tourId: "t3",
    status: "won",
    assignee: "Amir",
    createdAt: "2026-08-15",
    country: "Misr",
    city: "Sharm El Sheikh",
    hotel: "Red Sea Resort",
    flightDates: "2026-08-01 — 2026-08-08",
    adults: 2,
    childrenAges: "4",
    netCost: 1100,
    grossPrice: 1450,
    paidAmount: 1450,
    paidAmountUzs: 18270000,
  }),
  lead({
    id: "l8",
    name: "Rustam Qodirov",
    phone: "+998 94 333 44 55",
    tourId: "t1",
    status: "proposal_sent",
    assignee: "Sara",
    createdAt: "2026-09-09",
    country: "Tailand",
    city: "Bangkok",
    flightDates: "2026-12-05 — 2026-12-12",
    adults: 1,
    netCost: 900,
    grossPrice: 1100,
  }),
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "Dilshoda Nazarova",
    email: "dilshoda@mail.uz",
    phone: "+998 88 999 00 11",
    trips: 4,
    lastTrip: "Paris",
    status: "vip",
  },
  {
    id: "c2",
    name: "Bekzod Aliyev",
    email: "bekzod@mail.uz",
    phone: "+998 97 777 88 99",
    trips: 2,
    lastTrip: "Antalya",
    status: "active",
  },
  {
    id: "c3",
    name: "Madina Rakhimova",
    email: "madina@mail.uz",
    phone: "+998 91 222 33 44",
    trips: 1,
    lastTrip: "Malaysia",
    status: "active",
  },
  {
    id: "c4",
    name: "Jasur Karimov",
    email: "jasur@mail.uz",
    phone: "+998 90 111 22 33",
    trips: 0,
    lastTrip: "—",
    status: "idle",
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    leadId: "l6",
    customer: "Dilshoda Nazarova",
    route: "TAS → CDG",
    date: "2026-10-02",
    amountUsd: 2800,
    status: "paid",
  },
  {
    id: "b2",
    leadId: "l3",
    customer: "Bekzod Aliyev",
    route: "TAS → AYT",
    date: "2026-09-20",
    amountUsd: 980,
    status: "confirmed",
  },
  {
    id: "b3",
    leadId: "l4",
    customer: "Madina Rakhimova",
    route: "TAS → KUL",
    date: "2026-11-12",
    amountUsd: 1650,
    status: "new",
  },
  {
    id: "b4",
    leadId: "l5",
    customer: "Otabek Tursunov",
    route: "TAS → ICN",
    date: "2026-09-28",
    amountUsd: 3100,
    status: "completed",
  },
];

export const MOCK_MANAGER_SPENDS: ManagerSpend[] = [
  {
    id: "ms1",
    manager: "Sara Employee",
    item: "Ofis uchun naqd",
    amountUsd: 120,
    date: "2026-09-03",
    note: "Kassa",
  },
  {
    id: "ms2",
    manager: "Amir Admin",
    item: "Mijoz kutib olish",
    amountUsd: 85,
    date: "2026-09-07",
    note: "Transport",
  },
  {
    id: "ms3",
    manager: "Sara Employee",
    item: "SIM / internet",
    amountUsd: 40,
    date: "2026-09-09",
    note: "",
  },
];

export function getStats(role: User["role"]): DashboardStats {
  const fin = computeFinance(MOCK_LEADS, MOCK_MANAGER_SPENDS);
  const activeBookings = MOCK_BOOKINGS.filter(
    (b) => b.status !== "cancelled" && b.status !== "completed",
  ).length;
  const base: DashboardStats = {
    leads: MOCK_LEADS.filter((l) => l.status === "new_lead").length,
    activeBookings,
    tasksDue: MOCK_TOURS.length,
    conversion: "38%",
  };
  if (role === "admin") {
    return {
      ...base,
      revenueUsd: fin.revenueUsd,
      expensesUsd: fin.expensesUsd,
      profitUsd: fin.profitUsd,
      managerSpendUsd: fin.managerSpendUsd,
      operatorCostUsd: fin.operatorCostUsd,
    };
  }
  return base;
}
